/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaregresion;

import javax.swing.JOptionPane;

/**
 *
 * @author ivonls
 */
public class Principal extends javax.swing.JFrame {
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pts = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tiempo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        asistencia = new javax.swing.JTextField();
        calcular = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        certeza = new javax.swing.JTextField();
        eficiencia = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        limpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("¿Cuántos puntos doy?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, 40));

        jLabel2.setFont(new java.awt.Font("Bauhaus 93", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¿Cuántos puntos doy?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tiempo jugado (minutos): ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        pts.setBackground(java.awt.SystemColor.controlShadow);
        pts.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        pts.setForeground(new java.awt.Color(0, 0, 0));
        pts.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(pts, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 200, 30));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Asistencias: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        tiempo.setBackground(java.awt.SystemColor.controlShadow);
        tiempo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tiempo.setForeground(new java.awt.Color(0, 0, 0));
        tiempo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoActionPerformed(evt);
            }
        });
        getContentPane().add(tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 200, 30));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Puntos: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        asistencia.setBackground(java.awt.SystemColor.controlShadow);
        asistencia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        asistencia.setForeground(new java.awt.Color(0, 0, 0));
        asistencia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        asistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asistenciaActionPerformed(evt);
            }
        });
        getContentPane().add(asistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 200, 30));

        calcular.setBackground(new java.awt.Color(102, 255, 102));
        calcular.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        calcular.setForeground(new java.awt.Color(0, 0, 0));
        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
        getContentPane().add(calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Eficiencia ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, 20));

        certeza.setEditable(false);
        certeza.setBackground(new java.awt.Color(255, 153, 0));
        certeza.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        certeza.setForeground(new java.awt.Color(0, 0, 0));
        certeza.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(certeza, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 130, 30));

        eficiencia.setEditable(false);
        eficiencia.setBackground(new java.awt.Color(255, 153, 0));
        eficiencia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        eficiencia.setForeground(new java.awt.Color(0, 0, 0));
        eficiencia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(eficiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 200, 30));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nivel de certeza");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, 30));

        limpiar.setBackground(new java.awt.Color(153, 153, 255));
        limpiar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        limpiar.setForeground(new java.awt.Color(0, 0, 0));
        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 100, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\f2.jpg")); // NOI18N
        jLabel4.setText("Cuantos puntos doy");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        int asistencias,efi,pt;
        float time,c;
        c=(float) (100-36.3872);
        try{
            asistencias= Integer.parseInt(asistencia.getText());
            pt=Integer.parseInt(pts.getText());
            pt=Integer.parseInt(pts.getText());
            time=Float.parseFloat(tiempo.getText());
            efi= (int) (2.083*asistencias+0.2318*time+0.5824*pt+14.6793);
            eficiencia.setText(String.valueOf(efi)+"%");
            certeza.setText(String.valueOf(c)+"%");
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Aguno de los datos no es un número");
            asistencia.setText("");
            tiempo.setText("");
            pts.setText("");
            eficiencia.setText("");
            certeza.setText("");
            
    	}
       certeza.setText("");
    }//GEN-LAST:event_calcularActionPerformed

    private void asistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asistenciaActionPerformed

    private void tiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiempoActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        asistencia.setText("");
        tiempo.setText("");
        pts.setText("");
        eficiencia.setText("");
        certeza.setText("");
    }//GEN-LAST:event_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField asistencia;
    private javax.swing.JButton calcular;
    private javax.swing.JTextField certeza;
    private javax.swing.JTextField eficiencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton limpiar;
    private javax.swing.JTextField pts;
    private javax.swing.JTextField tiempo;
    // End of variables declaration//GEN-END:variables
}
